name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}
#     env:
#       VITE_apiKey : ${{ secrets.VITE_apiKey }}
#       VITE_authDomain : ${{ secrets.VITE_authDomain }}
#       VITE_projectId : ${{ secrets.VITE_projectId }}
#       VITE_storageBucket : ${{ secrets.VITE_storageBucket }}
#       VITE_messagingSenderId : ${{ secrets.VITE_messagingSenderId }}
#       VITE_appId : ${{ secrets.VITE_appId }}
      
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run build
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB2 }}
          publish_dir: ./dist
