name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    env:
      VITE_INTERNAL: true
      VITE_apiKey : "AIzaSyBzxFOF7P9rM5UvpKyUxHqlghUNJeuZzK8"
      VITE_authDomain : "april-bill.firebaseapp.com"
      VITE_projectId : "april-bill"
      VITE_storageBucket : "april-bill.appspot.com"
      VITE_messagingSenderId : "359825891077"
      VITE_appId : "1:359825891077:web:f421390c6f59d71f5ea16c"
      
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run build
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB2 }}
          publish_dir: ./dist
